main: net.viedantmc.BlazinNames.Main
name: BlazinNames
version: 0.7.2
author: Blazin_
api-version: 1.13
depend: [HeadDatabase, CMI, LuckPerms]

commands:
  namecolor:
    aliases: color
    permission: bn.namecolor
  nickname:
    aliases: nick
    permission: bn.nickname
