main: net.viedantmc.BlazinNames.Main
name: BlazinNames
version: 1.0
author: Laust & Blazin_
api-version: 1.13
depend: [HeadDatabase, CMI, LuckPerms]
softdepend: [HeadDatabase]

commands:
  namecolor:
    aliases: color
    permission: bn.namecolor
  nickname:
    aliases: nick
    permission: bn.nickname
