main: net.viedantmc.BlazinNames.Main
name: BlazinNames
version: 1.5
author: Laustz & Blazin_
api-version: 1.13
loadbefore: [CMI, LuckPerms]
depend: [CMI, LuckPerms]

commands:
  namecolor:
    aliases: color
    permission: bn.namecolor
  nickname:
    aliases: nick
    permission: bn.nickname
