main: net.viedantmc.BlazinNames.Main
name: BlazinNames
version: 0.7.2
author: Blazin_
api-version: 1.13
depend: [HeadDatabase]

commands:
  namecolor:
    aliases: color
  nickname:
    aliases: nick