main: net.viedantmc.BlazinNames.Main
name: BlazinNames
version: 1.1
author: Laust & Blazin_
api-version: 1.13
loadbefore: [CMI, LuckPerms, HeadDatabase]
depend: [CMI, LuckPerms, HeadDatabase]

commands:
  namecolor:
    aliases: color
    permission: bn.namecolor
  nickname:
    aliases: nick
    permission: bn.nickname
